import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { KeyRound, Plus, RefreshCw, X } from 'lucide-react';
import { PortalSidebar, ProfileMenu, httpService, initApiConfig } from '@notify-ui/shared';
import '../../events/src/styles/global.css';

type Client = { id: string; clientId: string; applicationName?: string; basePackage?: string; status?: string; expiresAt?: string; createdAt?: string };
type Credentials = { clientId: string; tenantId: string; apiKey: string; apiSecret: string; expiresAt: string };

initApiConfig({ baseURL: '', getAccessToken: () => document.cookie.match(/notify_access_token=([^;]+)/)?.[1] ?? null });

function ClientsApp() {
  const [clients, setClients] = useState<Client[]>([]);
  const [creating, setCreating] = useState(false);
  const [credentials, setCredentials] = useState<Credentials | null>(null);
  const load = async () => setClients(await httpService.get<Client[]>('/api/admin/clients', { ttlMs: 0 }));
  useEffect(() => { void load(); }, []);
  return <div className="app-shell"><PortalSidebar /><header className="topbar"><div><div className="topbar-title">Clients</div><div className="topbar-subtitle">Applications registered for this tenant</div></div><ProfileMenu /></header><main className="main-content"><section className="card"><div className="card-header"><span className="card-title"><KeyRound size={15} /> Clients</span><div style={{ display: 'flex', gap: 8 }}><button className="btn-icon" title="Refresh clients" onClick={() => void load()}><RefreshCw size={14} /></button><button className="btn btn-primary" onClick={() => setCreating(true)}><Plus size={14} /> New client</button></div></div><ClientTable clients={clients} /></section></main>{creating && <ClientForm onClose={() => setCreating(false)} onCreated={async credential => { await load(); setCreating(false); setCredentials(credential); }} />}{credentials && <CredentialsDialog credentials={credentials} onClose={() => setCredentials(null)} />}</div>;
}

function ClientTable({ clients }: { clients: Client[] }) { return <div style={{ overflowX: 'auto' }}><table className="data-table"><thead><tr><th>Application</th><th>Client ID</th><th>Base Package</th><th>Status</th><th>Expires</th><th>Created</th></tr></thead><tbody>{clients.map(client => <tr key={client.id}><td>{client.applicationName || '—'}</td><td className="mono" style={{ color: '#fde047' }}>{client.clientId}</td><td className="mono">{client.basePackage || '—'}</td><td>{client.status || 'ACTIVE'}</td><td>{client.expiresAt || 'Never'}</td><td>{client.createdAt ? new Date(client.createdAt).toLocaleString() : '—'}</td></tr>)}{!clients.length && <tr><td colSpan={6} style={{ textAlign: 'center', padding: 40, color: '#8d855f' }}>No clients registered for this tenant.</td></tr>}</tbody></table></div>; }
function ClientForm({ onClose, onCreated }: { onClose: () => void; onCreated: (credentials: Credentials) => Promise<void> }) { const [applicationName, setApplicationName] = useState(''); const [basePackage, setBasePackage] = useState(''); const [saving, setSaving] = useState(false); const save = async () => { setSaving(true); try { const result = await httpService.post<Credentials>('/client/generate', { data: { applicationName, basePackage }, successModal: null }); await onCreated(result.data); } finally { setSaving(false); } }; return <div className="modal-overlay"><div className="modal-box"><div className="modal-header"><span className="modal-title">Generate client</span><button className="btn-icon" onClick={onClose}><X size={15} /></button></div><div className="modal-body" style={{ display: 'grid', gap: 12 }}><label className="form-group"><span className="form-label">Application name</span><input className="form-input" value={applicationName} onChange={event => setApplicationName(event.target.value)} /></label><label className="form-group"><span className="form-label">Base package</span><input className="form-input" value={basePackage} onChange={event => setBasePackage(event.target.value)} placeholder="com.example.application" /></label></div><div className="modal-footer"><button className="btn btn-ghost" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={!applicationName.trim() || saving} onClick={() => void save()}>{saving ? 'Generating...' : 'Generate'}</button></div></div></div>; }
function CredentialsDialog({ credentials, onClose }: { credentials: Credentials; onClose: () => void }) { return <div className="modal-overlay"><div className="modal-box"><div className="modal-header"><span className="modal-title">Client credentials</span><button className="btn-icon" onClick={onClose}><X size={15} /></button></div><div className="modal-body" style={{ display: 'grid', gap: 12 }}><p style={{ color: '#facc15', margin: 0 }}>Store the secret now. It is not shown in the client list.</p><Credential label="Client ID" value={credentials.clientId} /><Credential label="API Key" value={credentials.apiKey} /><Credential label="API Secret" value={credentials.apiSecret} /></div><div className="modal-footer"><button className="btn btn-primary" onClick={onClose}>Done</button></div></div></div>; }
function Credential({ label, value }: { label: string; value: string }) { return <label className="form-group"><span className="form-label">{label}</span><input className="form-input mono" value={value} readOnly /></label>; }
createRoot(document.getElementById('root')!).render(<ClientsApp />);
